{
    'name': 'Tattoo',
    'version': '1.0',
    'category': 'Design',
    'description': '',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_account_payment',
        'appointment_hr',
        'appointment_sms',
        'base_vat',
        'crm_enterprise',
        'hr_skills',
        'product_barcodelookup',
        'sale_crm',
        'sale_pdf_quote_builder',
        'sale_planning',
        'sale_purchase',
        'sign',
        'survey',
        'website_appointment',
        'website_appointment_crm',
        'website_knowledge',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/mail_template.xml',
        'data/appointment_resource.xml',
        'data/crm_stage.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_attribute.xml',
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/uom_uom.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/sign_template.xml',
        'data/sign_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/appointment_type.xml',
        'demo/crm_tag.xml',
        'demo/crm_team.xml',
        'demo/website.xml',
        'demo/ir_ui_view.xml',
        'demo/account_analytic_plan.xml',
        'demo/hr_department.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/calendar_event.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/hr_employee.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
    ],
    'license': 'OPL-1',
    'assets': {'web.assets_backend': ['tattoo/static/src/js/my_tour.js']},
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
    ],
    'images': [
        'images/main.png',
    ],
}