{
    'name': 'Real Estate',
    'category': 'Real Estate/Brokerage',
    'summary': 'Estate summary',
    'description': 'Estate description',
    'license': 'GPL-3',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/estate_property_views.xml',
        'views/estate_property_tag_views.xml',
        'views/estate_property_offer_views.xml',
        'views/estate_property_type_views.xml',
        'views/res_user_views.xml',
        'views/estate_menus.xml',
        'report/estate_property_templates.xml',
        'report/estate_property_reports.xml',
        'report/res_users_templates.xml',
        'report/res_users_reports.xml',
    ],
    'demo': [
        'demo/estate.property.type.csv',
        'demo/estate.property_demo.xml',
        'demo/estate.property.offer_demo.xml',
    ],
    'application': True,
    'installable': True,
}
