{
    "name": "Estate",
    "version": "1.0",
    "category": "Tutorials",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/estate_property_offer.xml",
        "views/estate_property_type.xml",
        "views/estate_property_tag.xml",
        "views/estate_property_views.xml",
        "views/estate_menus.xml",
        "views/res_users_views.xml",
        "data/estate_property_data.xml",
        "data/estate_property_offer_data.xml",
    ],
    "application": True,
    "author": "Prerana Yesugade",
    "license": "LGPL-3",
}
